### ISSUE TITLE
VisibleDeprecationWarning when running "bins.py"

### ISSUE THREAD

**Issue by JuanmaMedina** [koszullab/meta3Cbox#1]
Good morning!

I am currently running the fourth step of the `meta3box ` pipeline, i.e. the binning process, with these parameters:
`bash meta3c.sh binning --n-bins 100 --iter 300 -p metabox_project`

However, I ran into some troubles which I think are related to the arguments associated to read-in functions from `Biopython`

I hope you can help me out here! The version of `Biopython` that I am currently using is 1.68
If you need further information, I will be happy to provide it.

Best,
Juanma

Here is the full error report:

**Drawing enrichment vs. size plots...
Drawing distribution violinplot...
Extracting bin subnetworks and matrices...
Loading partition...
Loading network...
Extracting bin FASTA files...**

/Bin/meta3Cbox/bins.py:155: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  dtype=None))
Traceback (most recent call last):
  File "/Bin/meta3Cbox/bins.py", line 305, in <module> 
    chunk_size=chunk_size)
  File "/Bin/meta3Cbox/bins.py", line 177, in extract_fasta
    sequence = str(genome[header_name][pos_start:pos_end])
  File "/usr/local/home/anaconda3/envs/meta3cbox/lib/python2.7/site-packages/Bio/Seq.py", line 235, in __getitem__
    return Seq(self._data[index], self.alphabet)
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by baudrly** [comment]
Hello, in lines 173 to 175:

                pos_start = chunk * chunk_size
                pos_end = min((chunk + 1) * chunk_size,
                              len(genome[header_name]))

could you try replacing them with 

                pos_start = int(chunk * chunk_size)
                pos_end = int(min((chunk + 1) * chunk_size,
                                  len(genome[header_name])))

and see if it works? I don't have an error on my machine so it could be a version of Biopython that raises an error with float indices.

As for the VisibleDeprecationWarning, it seems to be unrelated to your issue, though it may need fixing in the future.

**Comment by JuanmaMedina** [comment]
Hello Lyam. Thanks for the quick answer!

I re-run the pipeline again with those changes applied in the `bins.py` script, but I am afraid I am still encountering an error regarding those lines. More specifically:

/Bin/meta3Cbox/bins.py:155: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  dtype=None))
Traceback (most recent call last):
  File "/Bin/meta3Cbox/bins.py", line 305, in <module>
    chunk_size=chunk_size)
  File "/Bin/meta3Cbox/bins.py", line 173, in extract_fasta
    pos_start = int(chunk * chunk_size)
ValueError: invalid literal for int() with base 10: ''

Thanks in advance!

**Comment by baudrly** [comment]
In line 274:

    parser.add_argument('-c', '--chunk-size',

try replacing it with

    parser.add_argument('-c', '--chunk-size', type=int,

If it still fails, could you post the exact command you ran? 
* If you directly ran `bins.py`, please post the exact line with all the arguments.
* If you ran `binning.sh`, please post the contents of your `config.sh` file, assuming you didn't touch it afterwards.

**Comment by JuanmaMedina** [comment]
Hello Lyam,

Replacing that line in `bins.py` indeed fixes the issue! Thanks!

Specifically, the line that I was running to perform this 4th step was:

`bash meta3c.sh binning --n-bins 100 --iter 300 -p metabox_project`

However, I must notify you that the VisibleDeprecationError still appears. Just in case this is useful in the near future:

```
/Bin/meta3Cbox/bins.py:155: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
dtype=None))
```

I will soon open a new issue to specify some of the bugs that I encountered when running this pipeline, in case you want to work on them.

Best,
Juanma
